#!/bin/bash
#
# Raspberry Pi Voice Client Setup Script
#
# Usage:
#   curl -sSL https://your-repo/raspberry_pi/setup.sh | bash
#   OR
#   bash setup.sh

set -e

echo "════════════════════════════════════════════════════════════════"
echo "  Raspberry Pi Voice Client Setup"
echo "════════════════════════════════════════════════════════════════"
echo ""

# Check if running on Raspberry Pi
if [ ! -f /proc/device-tree/model ] || ! grep -q "Raspberry Pi" /proc/device-tree/model 2>/dev/null; then
    echo "⚠️  Warning: This script is designed for Raspberry Pi"
    echo "   It may not work correctly on other systems"
    read -p "Continue anyway? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

# Update system
echo "📦 Updating system packages..."
sudo apt-get update -qq

# Install Python
echo "🐍 Installing Python 3..."
sudo apt-get install -y python3 python3-pip python3-dev

# Install audio libraries
echo "🔊 Installing audio libraries..."
sudo apt-get install -y portaudio19-dev libasound2-dev

# Install GPIO library
echo "🔌 Installing GPIO library..."
sudo apt-get install -y python3-rpi.gpio || echo "⚠️  GPIO install failed (not on RPi?)"

# Install Git
echo "📦 Installing Git..."
sudo apt-get install -y git

# Clone or update repository
INSTALL_DIR="$HOME/mqtt_voice_client"
if [ -d "$INSTALL_DIR" ]; then
    echo "📁 Updating existing installation..."
    cd "$INSTALL_DIR"
    git pull
else
    echo "📥 Cloning repository..."
    read -p "Enter repository URL (or press Enter to skip): " REPO_URL
    if [ -n "$REPO_URL" ]; then
        git clone "$REPO_URL" "$INSTALL_DIR"
        cd "$INSTALL_DIR/raspberry_pi/mqtt_voice_client"
    else
        echo "⚠️  No repository provided. Please manually copy the mqtt_voice_client directory."
        read -p "Press Enter when files are in $INSTALL_DIR..."
        cd "$INSTALL_DIR"
    fi
fi

# Install Python dependencies
echo "📦 Installing Python dependencies..."
pip3 install -r requirements.txt

# Test audio
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  Audio Test"
echo "════════════════════════════════════════════════════════════════"
echo ""
read -p "Test microphone? (Y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Nn]$ ]]; then
    echo "🎤 Recording 3 seconds..."
    arecord -d 3 -f cd /tmp/test.wav
    echo "🔊 Playing back..."
    aplay /tmp/test.wav
    rm /tmp/test.wav
fi

# Configure device
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  Device Configuration"
echo "════════════════════════════════════════════════════════════════"
echo ""

read -p "Enter device ID (e.g., rpi-toy-001): " DEVICE_ID
read -p "Enter backend URL (e.g., https://your-backend.run.app): " API_URL
read -p "Enter language (e.g., hi-IN, ta-IN, en-IN): " LANGUAGE

echo ""
echo "Select domain:"
echo "  1. Education (CBSE)"
echo "  2. Wellbeing"
echo "  3. Sustainability"
echo "  4. Financial Literacy"
echo "  5. Entrepreneurship"
echo "  6. Other"
read -p "Enter choice (1-6): " DOMAIN_CHOICE

case $DOMAIN_CHOICE in
    1) DOMAIN="education" ;;
    2) DOMAIN="wellbeing" ;;
    3) DOMAIN="sustainability" ;;
    4) DOMAIN="financial-literacy" ;;
    5) DOMAIN="entrepreneurship" ;;
    *) read -p "Enter domain name: " DOMAIN ;;
esac

echo ""
echo "Select TTS voice:"
echo "  1. Hindi Female"
echo "  2. Hindi Male"
echo "  3. Tamil Female"
echo "  4. Tamil Male"
echo "  5. English (Indian) Female"
echo "  6. Other"
read -p "Enter choice (1-6): " VOICE_CHOICE

case $VOICE_CHOICE in
    1) TTS_VOICE="indic-hindi-female" ;;
    2) TTS_VOICE="indic-hindi-male" ;;
    3) TTS_VOICE="indic-tamil-female" ;;
    4) TTS_VOICE="indic-tamil-male" ;;
    5) TTS_VOICE="indic-english-female" ;;
    *) read -p "Enter voice name: " TTS_VOICE ;;
esac

# Create configuration file
CONFIG_FILE="$INSTALL_DIR/config.py"
cat > "$CONFIG_FILE" << EOF
# Voice Client Configuration
# Generated by setup.sh

DEVICE_ID = "$DEVICE_ID"
API_URL = "$API_URL"
LANGUAGE = "$LANGUAGE"
DOMAIN = "$DOMAIN"
TTS_VOICE = "$TTS_VOICE"
TTS_PROVIDER = "qwen"
SAMPLE_RATE_HZ = 16000
EOF

echo "✅ Configuration saved to $CONFIG_FILE"

# Test connection
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  Testing Backend Connection"
echo "════════════════════════════════════════════════════════════════"
echo ""

if curl -s -f "$API_URL/health" > /dev/null; then
    echo "✅ Backend is accessible"
else
    echo "❌ Backend is not accessible"
    echo "   URL: $API_URL"
    echo "   Please check the URL and try again"
fi

# Register device
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  Device Registration"
echo "════════════════════════════════════════════════════════════════"
echo ""

cat > /tmp/register_device.py << 'EOF'
import sys
sys.path.insert(0, ".")
from mqtt_voice_client import VoiceClient
from config import *

try:
    client = VoiceClient(
        device_id=DEVICE_ID,
        api_url=API_URL,
        language=LANGUAGE,
    )
    
    result = client.register_device(
        domain=DOMAIN,
        tts_voice=TTS_VOICE,
        tts_provider=TTS_PROVIDER,
        capabilities={
            "stt": True,
            "tts": True,
            "chat": True,
            "streaming": False,
        },
    )
    
    print("✅ Device registered successfully!")
    print(f"   Device ID: {DEVICE_ID}")
    print(f"   Domain: {DOMAIN}")
    print(f"   Language: {LANGUAGE}")
    print(f"   Voice: {TTS_VOICE}")
except Exception as e:
    print(f"❌ Registration failed: {e}")
    sys.exit(1)
EOF

cd "$INSTALL_DIR"
python3 /tmp/register_device.py
rm /tmp/register_device.py

# Setup complete
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  Setup Complete! 🎉"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Your voice toy is ready to use!"
echo ""
echo "To test:"
echo "  cd $INSTALL_DIR/examples"
echo "  python3 full_voice_toy.py"
echo ""
echo "To configure auto-start:"
echo "  sudo cp $INSTALL_DIR/voice-toy.service /etc/systemd/system/"
echo "  sudo systemctl enable voice-toy.service"
echo "  sudo systemctl start voice-toy.service"
echo ""
echo "For help, see:"
echo "  $INSTALL_DIR/README.md"
echo ""
